version: '3.4'

networks:
  web:
    external:
      name: web
services:
  storefront:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront.entrypoints=http"
      - "traefik.http.routers.storefront.rule=Host(`storefront.example.com`)"
      - "traefik.http.middlewares.storefront-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.storefront.middlewares=storefront-https-redirect"
      - "traefik.http.routers.storefront-secure.entrypoints=https"
      - "traefik.http.routers.storefront-secure.rule=Host(`storefront.example.com`)"
      - "traefik.http.routers.storefront-secure.tls=true"
      - "traefik.http.routers.storefront-secure.service=storefront"
      - "traefik.http.services.storefront.loadbalancer.server.port=4000"
      - "traefik.docker.network=web"

    networks:
      web:
