version: "3.4"

networks:
  web:
    external:
      name: web
  internal:
    external:
      name: internal

services:
  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - internal

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=Host(`health.craflo.com`)"
      - "traefik.http.middlewares.web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web.middlewares=web-https-redirect"
      - "traefik.http.routers.web-secure.entrypoints=https"
      - "traefik.http.routers.web-secure.rule=Host(`health.craflo.com`)"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=9000"
      - "traefik.docker.network=web"
    #Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    #command: --templates https://craflo.com/templates.json
    networks:
      - web
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:
